workflows:
  android_ios_release:
    name: Android & iOS Release
    max_build_duration: 60
    instance_type: mac_m2

    environment:
      flutter: stable
      # группы переменных — создай их в Codemagic → Environment variables
      groups:
        - android_secrets
        - ios_secrets
        - backend

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ios/Pods

    scripts:
      - name: Print versions
        script: |
          flutter --version
          dart --version
          java -version

      - name: Restore Firebase & signing files (bash only)
        script: |
          set -e
          mkdir -p android/app
          mkdir -p ios/Runner

          # keystore
          if [ -n "$CM_KEYSTORE" ]; then
            echo "$CM_KEYSTORE" | base64 -d > android/app/onde-release.keystore
            echo "Keystore restored: $(wc -c < android/app/onde-release.keystore) bytes"
          fi

          # key.properties для подписи Android
          cat > android/key.properties <<EOF
          storePassword=${CM_KEYSTORE_PASSWORD}
          keyPassword=${CM_KEY_PASSWORD}
          keyAlias=${CM_KEY_ALIAS}
          storeFile=onde-release.keystore
          EOF

          # google-services.json (Android)
          if [ -n "$CM_GOOGLE_SERVICES_JSON" ]; then
            echo "$CM_GOOGLE_SERVICES_JSON" | base64 -d > android/app/google-services.json
            echo "google-services.json size: $(wc -c < android/app/google-services.json) bytes"
          fi

          # GoogleService-Info.plist (iOS)
          if [ -n "$CM_GOOGLESERVICE_INFO_PLIST" ]; then
            echo "$CM_GOOGLESERVICE_INFO_PLIST" | base64 -d > ios/Runner/GoogleService-Info.plist
            echo "GoogleService-Info.plist size: $(wc -c < ios/Runner/GoogleService-Info.plist) bytes"
          fi

      - name: Flutter pub get
        script: flutter pub get

      - name: Build Android AAB
        script: |
          set -e
          # чистим Gradle, чтобы точно подхватился keystore
          (cd android && ./gradlew --no-daemon clean)
          flutter build appbundle --release \
            --target-platform android-arm,android-arm64,android-x64 \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
        artifacts:
          - build/app/outputs/bundle/release/*.aab
          - build/app/outputs/mapping/**/*.txt

      - name: Build iOS IPA (no codesign)
        script: |
          flutter build ipa --release --no-codesign \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
        artifacts:
          - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - $CM_NOTIFICATION_EMAIL
        notify:
          success: true
          failure: true