workflows:
  flutter_release:
    name: Onde • Android & iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 15.4
      vars:
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY

    cache:
      cache_paths:
        - ~/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - android/.gradle
        - ~/.gradle

    scripts:
      - name: Print versions
        script: |
          flutter --version
          dart --version
          java -version

      - name: Restore Firebase & signing files
        script: |
          set -e
          echo "$CM_GOOGLE_SERVICES_JSON" | base64 --decode > android/app/google-services.json
          mkdir -p ios/Runner
          echo "$CM_GOOGLESERVICE_INFO_PLIST" | base64 --decode > ios/Runner/GoogleService-Info.plist
          echo "$CM_KEYSTORE" | base64 --decode > android/app/onde-release.keystore
          cat > android/key.properties <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=../app/onde-release.keystore
          EOF

      - name: Flutter pub get
        script: flutter pub get

      - name: Build Android AAB
        script: flutter build appbundle --release --target-platform android-arm,android-arm64,android-x64

      - name: Build iOS IPA (no codesign)
        script: flutter build ipa --release --no-codesign

    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa